---
- name: Install dynamic configuration scripts
  copy:
    src: "../files/bin/{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - { src: "resize-lvm-root", dest: "/usr/local/bin/resize-lvm-root", mode: "0755" }
    - { src: "setup-dns", dest: "/usr/local/bin/setup-dns", mode: "0755" }

- name: Configure streamlined cloud-init configuration
  copy:
    dest: /etc/cloud/cloud.cfg
    mode: 0644
    content: |
      datasource_list: [
        NoCloud, ConfigDrive, OpenStack, Azure, GCE, Ec2, VMware, 
        OVF, MAAS, CloudStack, Hetzner, Oracle, None
      ]

      preserve_sources_list: true

      manage_resolv_conf: false

      cloud_init_modules:
       - migrator
       - seed_random
       - bootcmd
       - write-files
       - disk_setup
       - mounts
       - set_hostname
       - update_hostname
       - update_etc_hosts
       - users-groups
       - ssh

      cloud_config_modules:
       - runcmd

      cloud_final_modules:
       - final-message
       - power-state-change

      system_info:
        distro: opensuse
        ssh_svcname: sshd
        default_user:
          name: admin
          lock_passwd: true
          gecos: Cloud User
          groups: [users, wheel, dialout, cdrom, audio, video, plugdev]
          sudo: ["ALL=(ALL) NOPASSWD:ALL"]
          shell: /bin/bash

      bootcmd:
        - [/usr/local/bin/resize-lvm-root]

      runcmd:
        - systemctl daemon-reload
        - sleep 2
        - /usr/local/bin/setup-dns || true
        - systemctl restart nftables-firewall || true
        - systemctl restart docker || true
