---
- name: Create firewall-manager directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  with_items:
    - /etc/firewall-manager
    - /etc/firewall-manager/rules.d
    - /var/fwm-backups

- name: Install firewall management control script
  copy:
    src: ../files/firewall-manager/fwmctl
    dest: /usr/local/bin/fwmctl
    owner: root
    group: root
    mode: 0755

- name: Create firewall-manager systemd service
  copy:
    src: ../files/firewall-manager/firewall-manager.service
    dest: /etc/systemd/system/firewall-manager.service
    owner: root
    group: root
    mode: 0644

- name: Copy base firewall rules
  copy:
    src: ../files/firewall-manager/base.rules
    dest: /etc/firewall-manager/base.rules
    owner: root
    group: root
    mode: 0600

- name: Copy Docker-specific firewall rules
  copy:
    src: ../files/firewall-manager/10-docker.rules
    dest: /etc/firewall-manager/rules.d/10-docker.rules
    owner: root
    group: root
    mode: 0600

- name: Enable and start firewall-manager service
  systemd:
    name: firewall-manager
    enabled: yes
    daemon_reload: yes
    state: started
