---
- name: Create nftables-firewall directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  with_items:
    - /etc/nftables-firewall
    - /etc/nftables-firewall/rules.d
    - /var/nftables-firewall-backups

- name: Install nftables firewall control script
  copy:
    src: ../files/nftables-firewall/nfwctl
    dest: /usr/local/bin/nfwctl
    owner: root
    group: root
    mode: 0755

- name: Create nftables-firewall systemd service
  copy:
    src: ../files/nftables-firewall/nftables-firewall.service
    dest: /etc/systemd/system/nftables-firewall.service
    owner: root
    group: root
    mode: 0644

- name: Create base nftables rules
  copy:
    src: ../files/nftables-firewall/base.nft
    dest: /etc/nftables-firewall/base.nft
    owner: root
    group: root
    mode: 0600

- name: Create Docker-specific nftables rules
  copy:
    src: ../files/nftables-firewall/10-docker.nft
    dest: /etc/nftables-firewall/rules.d/10-docker.nft
    owner: root
    group: root
    mode: 0600
  when: "'docker' in ansible_facts.services and ansible_facts.services['docker']['state'] == 'running'"

- name: Enable and start nftables-firewall service
  systemd:
    name: nftables-firewall
    enabled: yes
    state: started
    daemon_reload: yes
