---
- name: Gather service facts
  service_facts:

- name: Tumbleweed specific tasks
  include_tasks: tumbleweed.yml
  when: ansible_distribution == 'openSUSE Tumbleweed'

- name: Install base packages
  include_tasks: packages.yml

- name: Configure cloud-init
  include_tasks: cloud-init.yml

- name: Configure DNS
  include_tasks: dns.yml

- name: Configure networking
  include_tasks: networking.yml

- name: Configure Docker
  include_tasks: docker.yml

- name: Configure system tuning
  include_tasks: system-tuning.yml

- name: Configure firewall
  include_tasks: firewall.yml
