---
- name: Disable GRUB splash
  lineinfile:
    path: /etc/default/grub
    regexp: ^GRUB_CMDLINE_LINUX_DEFAULT=
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="mitigations=auto quiet security=apparmor"'
  register: grub

- name: Regenerate GRUB
  command: grub2-mkconfig
  when: grub is changed

- name: Limit the total size of journald logs
  copy:
    dest: /etc/systemd/journald.conf.d/99-journald.conf
    content: |
     SystemMaxUse={{ systemd_journal_system_max_use }}

- name: Restart systemd-journald.service
  systemd:
    name: systemd-journald
    state: restarted
    enabled: yes

- name: Enable and start systemd-resolved.service
  systemd:
    name: systemd-resolved
    enabled: yes
    state: started

- name: Set up cloudflare dns
  copy:
    src: ../files/resolved-cloudflare.conf
    dest: /etc/systemd/resolved.conf.d/cloudflare.conf
    owner: root
    group: root
    mode: 0644

- name: Enable and start systemd-resolved.service
  systemd:
    name: systemd-resolved
    state: restarted

- name: Manage swap file entry in fstab.
  mount:
    name: none
    src: "{{ swap_file_path }}"
    fstype: swap
    opts: sw
    state: present

- name: Ensure swap file exists.
  command: >
    {{ swap_file_create_command }}
    creates='{{ swap_file_path }}'
  register: swap_file_create

- name: Set permissions on swap file.
  file:
    path: "{{ swap_file_path }}"
    owner: root
    group: root
    mode: 0600

- name: Make swap file if necessary.
  command: mkswap {{ swap_file_path }}
  when: swap_file_create is changed
  register: mkswap_result

- name: Run swapon on the swap file.
  command: swapon {{ swap_file_path }}
  when:
    - mkswap_result is changed

- name: Copy 99-sysctl.conf
  copy:
    src: ../files/99-sysctl.conf
    dest: /etc/sysctl.d/99-sysctl.conf
  register: sysctl

- name: Reload sysctl
  command: sysctl --system
  when: sysctl is changed

- name: Add the nf_conntrack module
  modprobe:
    name: nf_conntrack
    state: present

- name: Set nf_conntrack parameters
  copy:
    dest: /etc/modprobe.d/99-nf_conntrack.conf
    content: |
      options nf_conntrack hashsize=2500000

- name: Load nf_conntrack module
  copy:
    dest: /etc/modules-load.d/nf_conntrack.conf
    content: |
      nf_conntrack

- name: Enable and start systemd-modules-load.service
  systemd:
    name: systemd-modules-load
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Copy nf_conntrack parameters script
  copy:
    dest: /etc/nf_conntrack-params.sh
    content: |
      sysctl -w net/netfilter/nf_conntrack_tcp_loose=0
      sysctl -w net/netfilter/nf_conntrack_max=2000000
      sysctl --system
    mode: 0744

- name: Copy nf_conntrack parameters service
  copy:
    src: ../files/nf_conntrack-params.service
    dest: /etc/systemd/system/nf_conntrack-params.service
    owner: root
    group: root
    mode: 0644

- name: Enable and start nf_conntrack-params.service
  systemd:
    name: nf_conntrack-params
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Reload sysctl
  command: "{{ item }}"
  loop:
    - sysctl -w net.ipv4.route.flush=1
    - sysctl -w net.ipv6.route.flush=1
    - sysctl --system

- name: Create disable-transparent-huge-pages.service
  copy:
    src: ../files/disable-transparent-huge-pages.service
    dest: /etc/systemd/system/disable-transparent-huge-pages.service
    owner: root
    group: root
    mode: 0644

- name: Copy disable-transparent-huge-pages
  copy:
    src: ../files/disable-transparent-huge-pages
    dest: /etc/disable-transparent-huge-pages
    owner: root
    group: root
    mode: 0744

- name: Enable and start disable-transparent-huge-pages service
  systemd:
    name: disable-transparent-huge-pages
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Install iptables
  zypper:
    name: iptables
    state: present

- name: Create iptables directory
  file:
    path: /etc/iptables
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create iptables-startup.service
  copy:
    src: ../files/iptables.service
    dest: /etc/systemd/system/iptables.service
    owner: root
    group: root
    mode: 0644

- name: Create iptables-startup@.service
  copy:
    src: ../files/iptables@.service
    dest: /etc/systemd/system/iptables@.service
    owner: root
    group: root
    mode: 0644

- name: Copy iptables.rules
  copy:
    src: ../files/iptables.rules
    dest:  /etc/iptables/iptables.rules
    owner: root
    group: root
    mode: 0644

- name: Enable and start iptables.service
  systemd:
    name: iptables
    state: started
    enabled: yes
    daemon_reload: yes

- name: Create iptables-startup.service
  copy:
    src: ../files/iptables-startup.service
    dest: /etc/systemd/system/iptables-startup.service
    owner: root
    group: root
    mode: 0644

- name: Copy iptables-startup.sh
  copy:
    src: ../files/iptables-startup.sh
    dest: /etc/iptables-startup.sh
    owner: root
    group: root
    mode: 0744

- name: Enable and start iptables-startup.service
  systemd:
    name: iptables-startup.service
    state: stopped
    enabled: yes
    daemon_reload: yes

- name: Create ipset-blacklist configuration directory
  file:
    path: /etc/ipset-blacklist
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy range2cidr.awk
  copy:
    src: ../files/range2cidr.awk
    dest: /etc/ipset-blacklist/range2cidr.awk
    owner: root
    group: root
    mode: 0644

- name: Create ipset-blacklist.service
  copy:
    src: ../files/ipset-blacklist.service
    dest: /etc/systemd/system/ipset-blacklist.service
    owner: root
    group: root
    mode: 0644

- name: Copy ipset-blacklist.sh
  copy:
    src: ../files/ipset-blacklist.sh
    dest: /etc/ipset-blacklist.sh
    owner: root
    group: root
    mode: 0744

- name: Enable and start ipset-blacklist service
  systemd:
    name: ipset-blacklist.service
    state: restarted
    enabled: yes
    daemon_reload: yes
