---
- name: System provisioning with cloud-init support
  hosts: all
  become: yes

  tasks:
    - name: Gather service facts
      service_facts:

    - name: Install base packages
      include_tasks: tasks/packages.yml

    - name: Configure cloud-init
      include_tasks: tasks/cloud-init.yml

    - name: Configure DNS
      include_tasks: tasks/dns.yml

    - name: Configure networking
      include_tasks: tasks/networking.yml

    - name: Configure Docker
      include_tasks: tasks/docker.yml

    - name: Configure users and security
      include_tasks: tasks/users.yml

    - name: Configure system tuning
      include_tasks: tasks/system-tuning.yml

    - name: Configure firewall
      include_tasks: tasks/firewall.yml
