---
- name: Configure NetworkManager to not manage DNS
  copy:
    dest: /etc/NetworkManager/NetworkManager.conf
    mode: 0644
    content: |
      [main]
      dns=none
      rc-manager=unmanaged

      [ipv4]
      dns=127.0.0.1

- name: Restart NetworkManager
  service:
    name: NetworkManager
    state: restarted

- name: Enable and restart systemd-modules-load service
  systemd:
    name: systemd-modules-load
    state: restarted
    enabled: yes
    daemon_reload: yes
