---
- name: Configure NetworkManager to not manage DNS
  copy:
    dest: /etc/NetworkManager/NetworkManager.conf
    mode: 0644
    content: |
      [main]
      dns=none
      rc-manager=unmanaged

      [ipv4]
      dns=127.0.0.1

- name: Restart NetworkManager
  service:
    name: NetworkManager
    state: restarted

- name: Configure netfilter connection tracking parameters
  copy:
    dest: /etc/modprobe.d/99-nf_conntrack.conf
    content: |
      options nf_conntrack hashsize=250000
    owner: root
    group: root
    mode: 0644

- name: Configure netfilter modules to load at boot
  copy:
    dest: /etc/modules-load.d/nf_conntrack.conf
    content: |
      nf_conntrack
      nf_conntrack_ipv4
      nf_conntrack_ipv6
    owner: root
    group: root
    mode: 0644

- name: Enable and restart systemd-modules-load service
  systemd:
    name: systemd-modules-load
    state: restarted
    enabled: yes
    daemon_reload: yes
