---
- name: Install base system packages
  package:
    name:
      # Core system packages
      - cloud-init
      - growpart
      - python3-rpm

      # Container and DNS services
      - docker
      - dnscrypt-proxy
      - dnsmasq
      - crowdsec-firewall-bouncer

      # Essential utilities for scripts
      - unzip
      - curl
      - jq
      - wget
      - ca-certificates
    state: present

- name: Install virtualization guest tools and drivers
  package:
    name:
      # VMware guest tools
      - open-vm-tools

      # KVM/QEMU guest tools
      - qemu-guest-agent

      # Xen guest tools
      - xen-tools

    state: present

- name: Install HashiCorp Services
  include_tasks: install_hashicorp_service.yml
  loop: "{{ services }}"
  loop_control:
    loop_var: item

- name: Reload systemd
  systemd:
    daemon_reload: yes
