---
- name: Install base system packages
  package:
    name:
      # Core system packages
      - kernel-longterm
      - cloud-init
      - growpart
      - python3-rpm

      # Container and DNS services
      - docker
      - dnscrypt-proxy
      - dnsmasq

      # Essential utilities for scripts
      - unzip
      - curl
      - jq
      - wget
      - ca-certificates

    state: present

- name: Install virtualization guest tools and drivers
  package:
    name:
      # VMware guest tools
      - open-vm-tools

      # KVM/QEMU guest tools
      - qemu-guest-agent


      # Xen guest tools
      - xen-tools

    state: present

- name: Remove kernel-default
  package:
    name:
      - kernel-default
    state: absent
