---
- name: Install base system packages
  package:
    name:
      - kernel-longterm
      - cloud-init
      - docker
      - dnscrypt-proxy
      - dnsmasq
      - unzip
      - curl
      - wget
      - ca-certificates
    state: present

- name: Remove kernel-default
  package:
    name:
      - kernel-default
    state: absent

- name: Ensure cloud-init is enabled for boot
  service:
    name: cloud-init
    enabled: yes
