---
- name: Install base system packages
  package:
    name:
      # Core system packages
      - kernel-longterm
      - cloud-init
      - growpart

      # Container and DNS services
      - docker
      - dnscrypt-proxy
      - dnsmasq

      # Essential utilities for scripts
      - unzip
      - curl
      - jq
      - wget
      - ca-certificates

    state: present

- name: Install virtualization guest tools and drivers
  package:
    name:
      # VMware guest tools
      - open-vm-tools

      # KVM/QEMU guest tools
      - qemu-guest-agent

      # Hyper-V guest tools
#      - hyper-v

      # Xen guest tools
      - xen-tools

      # Google Cloud guest tools
#      - google-guest-agent
#      - google-guest-oslogin
#      - google-guest-configs
    state: present

- name: Remove kernel-default
  package:
    name:
      - kernel-default
    state: absent
