---
- name: Copy system sysctl configuration
  copy:
    src: ../files/99-sysctl.conf
    dest: /etc/sysctl.d/99-sysctl.conf
    owner: root
    group: root
    mode: 0644
  register: sysctl_config

- name: Reload sysctl configuration
  command: sysctl --system
  when: sysctl_config is changed
