---
- name: Clear repository configuration
  shell: rm -f /etc/zypp/repos.d/*.repo
  ignore_errors: true

- name: Add Tumbleweed repositories
  zypper_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    repo: "{{ item.url }}"
    priority: "{{ item.priority }}"
    auto_import_keys: yes
    state: present
  loop: "{{ tumbleweed_repos }}"

- name: Clean zypper cache
  shell: zypper clean --all && zypper --non-interactive refresh

- name: Install kernel-longterm
  zypper:
    name:
      - kernel-longterm
    state: present
  register: install_kernel

- name: Remove kernel-default
  zypper:
    name:
      - kernel-default
    state: absent
  register: remove_kernel

- name: Perform dist-upgrade
  zypper:
    name: '*'
    state: dist-upgrade
    update_cache: true
  register: upgrade_result
  failed_when: upgrade_result.rc not in [0, 107]

- name: Reboot the machine
  reboot:
  when: install_kernel.changed or remove_kernel.changed or upgrade_result.rc == 107
