---
- name: Remove CD/DVD repos
  shell: |
    ids=$(zypper lr --uri | awk -F'|' '/(cd|dvd):/ {print $1}' | xargs)
    if [ -n "$ids" ]; then
      zypper --non-interactive removerepo $ids
    else
      echo "No CD/DVD repos found"
    fi

- name: Install base system packages
  zypper:
    name:
      - kernel-longterm
    state: present
    update_cache: yes

- name: Remove kernel-default
  zypper:
    name:
      - kernel-default
    state: absent

- name: Reboot the machine
  reboot:
