---
- name: Install base system packages
  zypper:
    name:
      - kernel-longterm
    state: present
    update_cache: yes

- name: Remove kernel-default
  zypper:
    name:
      - kernel-default
    state: absent

- name: Reboot the machine
  reboot:
