---
- name: Add admin user to sudoers (cloud-init handles user creation and SSH keys)
  copy:
    content: 'admin ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/admin
    mode: 0400

- name: Set up admin ssh key for provisioning
  ansible.posix.authorized_key:
    user: admin
    key: "{{ provision_ssh_key_base64 | b64decode }}"
    state: present
    exclusive: True
